# Generated by Django 4.1.7 on 2023-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_value', models.IntegerField(max_length=500)),
                ('p_value', models.IntegerField(max_length=500)),
                ('k_value', models.IntegerField(max_length=500)),
                ('temp', models.IntegerField(max_length=500)),
                ('humidity', models.IntegerField(max_length=500)),
            ],
        ),
    ]
