# Generated by Django 4.1.7 on 2023-03-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='k_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='n_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='p_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='temp',
            field=models.IntegerField(),
        ),
    ]
